### ISSUE TITLE
multilingual version

### ISSUE THREAD

**Issue by WuGGu** [kylepulver/pathfindercharsheet#1]
Hi everyone, 

we would like to translate the sheets into german. So it would be great to get a feature for switching the language and everybody can use our german version.

**Comment by kylepulver** [comment]
Hi! What is the best way for you to do this? I'm still pretty new with Github so not sure if having a branch is possible, or if you want to start your own repo of a translated version that is also fine.

**Comment by kylepulver** [comment]
Thinking about it some more another option is that I could actually offload all of the text on the app into a file that can then be used to add more languages.  I think going down this route would be best for supporting more languages, it will just require another big update before it's possible.

**Comment by WuGGu** [comment]
I also think that this is the better solution. After the next update, i will push the changes for the language. So you can merge them into your release.

**Comment by kylepulver** [comment]
v1.4.00 introduces language support. if you look in the inc/lang folder you'll find en.php which is english.  You should be able to use this as a template for german, or any language.  I think the code for german is "de" so you would be making "de.php"  You can then set the language to use in config.php.

One thing that I havent addressed yet though is the layout of the app being effected by different languages.  Long words will probably break the layout until I can figure out a solution for that, but at least now you should be able to translate to any language you want.
